[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "Taskfarm"
version = "0.10"
description = "RG Simulation and Analysis engine"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["Taskfarm*"]
